/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CalculatorRi;

/**
 *
 * @author dell
 */
public class CalculatorRI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorRI
     */
    double Num1;
    double Num2;
    double Result;
    String operation;
    public CalculatorRI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button15 = new java.awt.Button();
        button16 = new java.awt.Button();
        jbutton17 = new java.awt.Button();
        button18 = new java.awt.Button();
        button19 = new java.awt.Button();
        button20 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 290, 50));

        button1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button1.setLabel("CE");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, 50));

        button2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button2.setLabel("BS");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 50));

        button3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button3.setLabel("±");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 60, 50));

        button4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button4.setLabel("C");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 60, 50));

        button5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button5.setLabel("8");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, 50));

        button6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button6.setLabel("7");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 50));

        button7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button7.setLabel("+");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 60, 50));

        button8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button8.setLabel("9");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 60, 50));

        button9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button9.setLabel("5");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 60, 50));

        button10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button10.setLabel("4");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        getContentPane().add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, 50));

        button11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button11.setLabel("-");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        getContentPane().add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 60, 50));

        button12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button12.setLabel("6");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        getContentPane().add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 60, 50));

        button13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button13.setLabel("2");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        getContentPane().add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 60, 50));

        button14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button14.setLabel("1");
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        getContentPane().add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 60, 50));

        button15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button15.setLabel("*");
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        getContentPane().add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 60, 50));

        button16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button16.setLabel("3");
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        getContentPane().add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 60, 50));

        jbutton17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbutton17.setLabel(".");
        jbutton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 60, 50));

        button18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button18.setLabel("0");
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        getContentPane().add(button18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 60, 50));

        button19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button19.setLabel("/");
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        getContentPane().add(button19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 60, 50));

        button20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button20.setLabel("=");
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        getContentPane().add(button20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 60, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
Enternumbers("7");        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
Enternumbers("8");        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
Enternumbers("9");        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
Enternumbers("4");        // TODO add your handling code here:
    }//GEN-LAST:event_button10ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
Enternumbers("5");        // TODO add your handling code here:
    }//GEN-LAST:event_button9ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
 Enternumbers("6");       // TODO add your handling code here:
    }//GEN-LAST:event_button12ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
Enternumbers("1");        // TODO add your handling code here:
    }//GEN-LAST:event_button14ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
Enternumbers("2");        // TODO add your handling code here:
    }//GEN-LAST:event_button13ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
Enternumbers("3");        // TODO add your handling code here:
    }//GEN-LAST:event_button16ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
Enternumbers("0");        // TODO add your handling code here:
    }//GEN-LAST:event_button18ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
       Num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       operation = "/";
    }//GEN-LAST:event_button19ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
   Num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       operation = "*";     // TODO add your handling code here:
    }//GEN-LAST:event_button15ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
  Num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       operation = "-";      // TODO add your handling code here:
    }//GEN-LAST:event_button11ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
  Num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       operation = "+";      // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
jTextField1.setText("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
   jTextField1.setText("");

String Fn, Sn;
Fn = String.valueOf(Num1);
Sn = String.valueOf(Num2);
Fn="";
Sn="";
// TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
double nums = Double.parseDouble(String.valueOf(jTextField1.getText()));
nums = nums * (-1);
jTextField1.setText(String.valueOf(nums));// TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
String bs = null;
if (jTextField1.getText().length() > 0)
{
StringBuilder sb =  new StringBuilder(jTextField1.getText());
sb.deleteCharAt(jTextField1.getText().length() - 1);
bs = sb.toString();
jTextField1.setText(bs);
}// TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void jbutton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton17ActionPerformed
if (! jTextField1.getText().contains("."))
{
jTextField1.setText(jTextField1.getText() +  jbutton17.getText());
}// TODO add your handling code here:
    }//GEN-LAST:event_jbutton17ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
Num2 = Double.parseDouble(jTextField1.getText());
if (operation == "+") {
Result = Num1 + Num2;
jTextField1.setText(String.valueOf(Result));
}// TODO add your handling code here:
else if (operation == "-") {
Result = Num1 - Num2;
jTextField1.setText(String.valueOf(Result));
}// TODO add your handling code here:
else if (operation == "/") {
Result = Num1 / Num2;
jTextField1.setText(String.valueOf(Result));
}// TODO add your handling code here:
else if (operation == "*") {
Result = Num1 * Num2;
jTextField1.setText(String.valueOf(Result));
}// TODO add your handling code here:
    }//GEN-LAST:event_button20ActionPerformed
private void Enternumbers(String q)
{
    String Nums = jTextField1.getText() + q;
    jTextField1.setText(Nums);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorRI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button18;
    private java.awt.Button button19;
    private java.awt.Button button2;
    private java.awt.Button button20;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JTextField jTextField1;
    private java.awt.Button jbutton17;
    // End of variables declaration//GEN-END:variables
}
